[package]
name = "otter"
version = "0.1.0"
edition = "2021"
description = "Lightweight secure code execution engine"
license = "MIT"

[lib]
name = "otter"
path = "src/lib.rs"

[[bin]]
name = "otter"
path = "src/main.rs"

[[test]]
name = "execution_test"
path = "tests/unit/execution_test.rs"

[[test]]
name = "api_test"
path = "tests/integration/api_test.rs"

[[test]]
name = "concurrent_test"
path = "tests/integration/concurrent_test.rs"

[[test]]
name = "sandbox_attacks"
path = "tests/sandbox_attacks/sandbox_attacks.rs"



[dependencies]
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
async-trait = "0.1"
anyhow = "1"
thiserror = "1"
dashmap = "5"
dotenvy = "0.15"
nix = { version = "0.29", features = ["resource", "signal", "user", "sched"] }
libseccomp = "0.3"


[dev-dependencies]
axum-test = "14"
tokio-test = "0.4"
futures = "0.3"